### ISSUE TITLE
V.:β17.02 "Hans" -> sollte auf ChangeLog verlinken

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D#22]

**Comment by GLSteiner** [comment]
![image](https://cloud.githubusercontent.com/assets/23318440/26297552/940604f2-3ed3-11e7-9871-4684bd8f4cfa.png)


Das wäre cool, wenn wir einen change log hätten!

Aber ich würde das mal ruhe lassen, solange die Oberfläche noch überlegen. Ich befürchte es die Versionsnummerierung wird eh rausfliegen da ihre Daseinsbenachrichtigung langsam schwindet

**Comment by oliveraustria** [comment]
Stimmt, das hat wirklich eine sehr geringe Prio aktuell :)

**Comment by GLSteiner** [comment]
Ich will jetzt keinen Changelog anfangen zu schreiben, wenn das Projekt bald fertig sein sollte. Damit hätten wir früher anfangen sollen. 

 Ich denke schon, dass die Oberfläche als ganzes sich eine höhere Priorität hat:

https://github.com/Ferienhort/F.H.I.E.L.D/issues/6

Und wenn es ohne Versionsnummer sauberer ist, dann fliegt die Versionsnummer raus 👍

**Comment by GLSteiner** [comment]
Ich habe jetzt einfach beschlossen, dass sie rausfliegt :)
