### ISSUE TITLE
Im Preis kann kein Komma verwendet werden

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D#23]
<img width="402" alt="f_h_i_e_l_d__-_ferienhort_in_ein_lustiger_datensatz" src="https://cloud.githubusercontent.com/assets/9258613/26270768/08e02cbc-3cfe-11e7-88c1-fb5a3a10c78d.png">

**Comment by GLSteiner** [comment]
Punkt geht, das eher ein Deutsch-Englisch Key bug. 

Muss ich mir genauer anschauen, vorerst bitte Punkt als Komma verwenden.
