### ISSUE TITLE
In Suchbox sind die Checkbox nach dem Text, sonst davor

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D#25]

**Comment by oliveraustria** [comment]
YEAH, alles sieht so ordentlich plötzlich aus! 👍

**Comment by GLSteiner** [comment]
Es ist unglaublich was für einen Unterschied gewisse Kleinigkeiten machen.

Danke dir für deine Inputs. Ich sehe sehr wohl das Resultat, aber ich komme auf viele Sachen nicht selber.

DANKE DIR FÜR DEINE INPUTS - Keep em coming!
