### ISSUE TITLE
Super Infopräsentation zum Herunterladen im Portal

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D#28]
Liebes F.H.I.E.L.D-Team,

es gab so eine tolle Präsentation zum Einsteigen - es wäre super, wenn man stets die neueste Präsentation als PDF im Portal herunterladen könnte.

Vielen Dank im Voraus,
Oliver

**Comment by GLSteiner** [comment]
Erstens mal danke für das Kompliment :)

Kurze Begriffserläuterung: Mit "Portal" meinst du den Bereich im FHIELD der nach dem Log in erscheint oder das FotoPortal des Ferienhortes?

**Comment by GLSteiner** [comment]
OK, ich habe es verstanden mit deinem anderen Post.

Ich würde die Issue gerne zu machen und den Vorschlag mit #6 Verbinden
