### ISSUE TITLE
Es wäre super, wenn man die zugeteilten Bereiche der Sticks auch im Portal sehen kann.

### ISSUE THREAD

**Issue by oliveraustria** [Ferienhort/F.H.I.E.L.D#29]
Aktuell sehe ich:

**Folgende Zahlen stehen noch für handschriftliche Beschriftung zur Verfügung
6000-6500**

Ich habe mir nur zusätzlich aufgeschrieben, Sticker 60000-60200.

**Comment by GLSteiner** [comment]
Gute Idee! Done!
