### ISSUE TITLE
Inventur erkennen verbessern

### ISSUE THREAD

**Issue by janniac2** [Ferienhort/F.H.I.E.L.D#34]
When inventur = active
automatically mark all scanned items as scanned

Bei Inventur wurde häufig das hakerl für "scan" vergessen, weshalb neu angelegte Items zwar angelegt, aber nicht gescannt wurden und daher nicht in der Inventur gezählt wurden.

**Comment by GLSteiner** [comment]
alle gescannten items werden gescannt 👍 

ich sehe eher denn Fehler, das die Software zwischen am Computer angelegt und am Handy angelegt unglücklich unterscheidet.

Also was ich raushöre, ist das neu angelegte Items automatisch gescannt werden sollen EGAL ob Computer oder Handy oder?
